project9/app1/urls.py
from django.urls import path
from app1.views import *
app_name='something'

urlpatterns=[
    path('first/',first,name='first'),

]

project9/app2/urls.py
from django.urls import path
from app2.views import *
app_name='special'

urlpatterns=[

    path('second/',second,name='second'),
]

project9/project9/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

project9/app1/models.py
from django.db import models

# Create your models here.

project9/app2/models.py
from django.db import models

# Create your models here.

project9/app1/views.py
from django.shortcuts import render

# Create your views here.

def first(request):
    return render(request,'first.html')

project9/app2/views.py
from django.shortcuts import render

# Create your views here.

def second(request):
    return render(request,'second.html')

project9/templates/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1><marquee>hi this is first page of html</marquee></h1>
        <a href='{% url "special:second" %}'><button>click here</button></a>
    </center>
    
</body>
</html>

project9/templates/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
    <h1><marquee>this is second html page</marquee></h1>
    <a href='{% url "something:first" %}'><button>click on</button></a>
    </center>
    
</body>
</html>